# Generated by Django 5.2.7 on 2025-10-20 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ambulance', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('seccion_vehiculo', models.JSONField(default=dict)),
                ('seccion_vitales', models.JSONField(default=dict)),
                ('seccion_inmovilizacion', models.JSONField(default=dict)),
                ('seccion_gaveta', models.JSONField(default=dict)),
                ('seccion_miscelaneos', models.JSONField(default=dict)),
                ('seccion_canalizacion', models.JSONField(default=dict)),
                ('seccion_ventilacion_monitor', models.JSONField(default=dict)),
                ('seccion_airway', models.JSONField(default=dict)),
                ('seccion_bulto_trauma', models.JSONField(default=dict)),
                ('seccion_entubacion', models.JSONField(default=dict)),
                ('seccion_medicamentos', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('ambulance', models.CharField(choices=[('CM1', 'CM1'), ('CM2', 'CM2'), ('CM3', 'CM3'), ('S56', 'S56')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway', 'Airway'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(default='Almacén', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('paramedic', models.CharField(max_length=100)),
                ('ambulance', models.CharField(max_length=50)),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('medicine', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paramedic', models.CharField(max_length=100)),
                ('ambulance', models.CharField(choices=[('CM1', 'CM1'), ('CM2', 'CM2'), ('CM3', 'CM3'), ('S56', 'S56')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(default='Almacén', max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
    ]
