# Generated by Django 5.2.7 on 2025-10-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceinventory',
            name='category',
            field=models.CharField(blank=True, choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway', 'Airway'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Vitales', 'Vitales'), ('Ventilacion & Monitor', 'Ventilacion & Monitor'), ('Equipo', 'Equipo'), ('Bulto de trauma', 'Bulto de trauma'), ('Entubacion', 'Entubacion')], max_length=50),
        ),
    ]
