# Generated by Django 5.2.7 on 2025-11-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_ambulancecheck_oxigeno_d_ambulancecheck_oxigeno_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Inmovilizacion', 'Inmovilización'), ('Canalizacion', 'Canalización'), ('Airway', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Miscelaneos', 'Misceláneos'), ('Entubacion', 'Entubación'), ('Equipo', 'Equipo')], default='Miscelaneos', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, default='unidades', max_length=50),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
    ]
