# Generated by Django 5.2.7 on 2025-11-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_inventoryitem_min_stock_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Entubación', 'Entubación'), ('Equipo', 'Equipo')], default='Miscelaneos', max_length=50),
        ),
    ]
