# Generated by Django 5.2.7 on 2025-11-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0006_alter_ambulanceinventory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_canalizacion',
            new_name='seccion_canalización',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_entubacion',
            new_name='seccion_entubación',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_gaveta',
            new_name='seccion_inmovilización',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_inmovilizacion',
            new_name='seccion_misceláneos',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_miscelaneos',
            new_name='seccion_suministros',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_ventilacion_monitor',
            new_name='seccion_ventilación_monitor',
        ),
    ]
