# Generated by Django 5.2.7 on 2025-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0009_alter_ambulancecheck_millage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecheck',
            name='firma_staff1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecheck',
            name='firma_staff2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancecheck',
            name='staff2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
