# Generated by Django 5.2.8 on 2025-11-29 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0014_alter_ambulanceinventory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance', models.CharField(blank=True, choices=[('CM1', 'CM1'), ('CM2', 'CM2'), ('CM3', 'CM3'), ('S56', 'S56')], help_text='Si se deja vacío, aplica como estándar general.', max_length=10, null=True)),
                ('recommended_quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_configs', to='ambulance.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventario Recomendado',
                'verbose_name_plural': 'Inventarios Recomendados',
                'unique_together': {('item', 'ambulance')},
            },
        ),
    ]
