# Generated by Django 5.2.8 on 2025-11-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0015_recommendedinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedinventory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='recommendedinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recommendedinventory',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendedinventory',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendedinventory',
            name='ambulance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='recommendedinventory',
            name='recommended_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='recommendedinventory',
            table='recommended_inventory',
        ),
    ]
