# Generated by Django 5.2.8 on 2025-12-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0016_alter_recommendedinventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedinventory',
            name='ambulance',
        ),
    ]
