# Generated by Django 5.2.8 on 2025-12-01 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0017_remove_recommendedinventory_ambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedinventory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendedinventory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='recommendedinventory',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
