# Generated by Django 5.2.8 on 2025-12-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0018_alter_recommendedinventory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_airway',
            new_name='seccion_equipo',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_bulto_trauma',
            new_name='seccion_medical_equipment',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_suministros',
            new_name='seccion_oxigeno_airway',
        ),
        migrations.RemoveField(
            model_name='ambulancecheck',
            name='seccion_ventilacion_monitor',
        ),
        migrations.RemoveField(
            model_name='ambulancecheck',
            name='seccion_vitales',
        ),
    ]
