# Generated by Django 5.2.7 on 2025-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_alter_ambulanceinventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecheck',
            name='oxigeno_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambulancecheck',
            name='oxigeno_m',
            field=models.IntegerField(default=0),
        ),
    ]
