# Generated by Django 5.2.7 on 2025-11-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0005_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceinventory',
            name='category',
            field=models.CharField(blank=True, choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Ventilacion & Monitor', 'Ventilacion & Monitor'), ('Equipo / Vitales', 'Equipo / Vitales'), ('Bulto de trauma', 'Bulto de trauma'), ('Entubación', 'Entubación')], max_length=50),
        ),
    ]
