# Generated by Django 5.2.7 on 2025-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0007_rename_seccion_canalizacion_ambulancecheck_seccion_canalización_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulancecheck',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_canalización',
            new_name='seccion_canalizacion',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_entubación',
            new_name='seccion_entubacion',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_inmovilización',
            new_name='seccion_inmovilizacion',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_misceláneos',
            new_name='seccion_miscelaneos',
        ),
        migrations.RenameField(
            model_name='ambulancecheck',
            old_name='seccion_ventilación_monitor',
            new_name='seccion_ventilacion_monitor',
        ),
        migrations.AddField(
            model_name='ambulancecheck',
            name='combustible',
            field=models.CharField(choices=[('Full', 'Full'), ('3/4', '3/4'), ('1/2', '1/2'), ('1/4', '1/4'), ('Empty', 'Empty')], default='Full', max_length=10),
        ),
        migrations.AddField(
            model_name='ambulancecheck',
            name='millage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ambulancecheck',
            unique_together={('date', 'ambulance', 'shift')},
        ),
    ]
