# Generated by Django 5.2.7 on 2025-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0008_alter_ambulancecheck_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancecheck',
            name='millage',
            field=models.IntegerField(default=0),
        ),
    ]
