# Generated by Django 5.2.7 on 2025-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0010_ambulancecheck_firma_staff1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Entubación', 'Entubación'), ('Equipo', 'Equipo')], default='Misceláneos', max_length=50),
        ),
    ]
