# Generated by Django 5.2.8 on 2025-11-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0011_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancerequisition',
            old_name='date',
            new_name='created_at',
        ),
    ]
